import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Grid } from "@mui/joy";
import { LoadingContext, LoadingProvider } from "./contexts/LoadingContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeRegistry options={{ key: "joy" }}>
          <LoadingProvider>
            <Grid container flexDirection="column" sx={{ height: "100vh" }}>
              <Navbar />
              {children}
              <Footer />
            </Grid>
          </LoadingProvider>
        </ThemeRegistry>
      </body>
    </html>
  );
}
